[build-system]
requires = [
    "setuptools>=46",
    "wheel",
    "setuptools_scm",
    "setuptools_scm_git_archive"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
line-length = 110
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 110